/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jnidebug_MainActivity */

#ifndef _Included_com_example_jnidebug_MainActivity
#define _Included_com_example_jnidebug_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jnidebug_MainActivity
 * Method:    getButtonString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jnidebug_MainActivity_getButtonString
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
